services:
  - type: web
    name: befiler-rag-api
    env: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: befiler-rag-db
          property: connectionString

databases:
  - name: befiler-rag-db
    plan: free
    postgresMajorVersion: 15
