spring:
  application:
    name: befiler-rag-assistant

  datasource:
    url: ${DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-3.5-turbo
        temperature: 0.7
    vectorstore:
      provider: pgvector
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
